plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace "com.sonu.app.polygon"
    compileSdk 37

    defaultConfig {
        minSdk 33
    }

    buildFeatures {
        compose true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    api platform(libs.androidx.compose.bom)
    api libs.androidx.activity.ktx
    api libs.androidx.compose.foundation
    api libs.androidx.compose.runtime
    api libs.androidx.compose.ui
}
